version: '3.8'

services:

    app:
        build: .
        image: fictional-octo-engine:${APP_VERSION}
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
        ports:
            - "5000:5000"

    redis:
      image: redis:7-alpine
